/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as CategorySlugCitySlugRouteImport } from './routes/$categorySlug.$citySlug'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelAgendaRouteImport } from './routes/painel.agenda'
import { Route as PainelCarteiraRouteImport } from './routes/painel.carteira'
import { Route as PainelDisponibilidadeRouteImport } from './routes/painel.disponibilidade'
import { Route as PainelNotificacoesRouteImport } from './routes/painel.notificacoes'
import { Route as PainelPerfilRouteImport } from './routes/painel.perfil'
import { Route as PainelServicosRouteImport } from './routes/painel.servicos'
import { Route as PainelDisputasDisputeIdRouteImport } from './routes/painel.disputas.$disputeId'
import { Route as PainelMensagensIndexRouteImport } from './routes/painel.mensagens.index'
import { Route as PainelMensagensConversationIdRouteImport } from './routes/painel.mensagens.$conversationId'
import { Route as ProfissionaisCitySlugProfileSlugRouteImport } from './routes/profissionais.$citySlug.$profileSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugCitySlugRoute = CategorySlugCitySlugRouteImport.update({
  id: '/$categorySlug/$citySlug',
  path: '/$categorySlug/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAgendaRoute = PainelAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCarteiraRoute = PainelCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => PainelRoute,
} as any)
const PainelDisponibilidadeRoute = PainelDisponibilidadeRouteImport.update({
  id: '/disponibilidade',
  path: '/disponibilidade',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNotificacoesRoute = PainelNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPerfilRoute = PainelPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PainelRoute,
} as any)
const PainelServicosRoute = PainelServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelDisputasDisputeIdRoute = PainelDisputasDisputeIdRouteImport.update({
  id: '/disputas/$disputeId',
  path: '/disputas/$disputeId',
  getParentRoute: () => PainelRoute,
} as any)
const PainelMensagensIndexRoute = PainelMensagensIndexRouteImport.update({
  id: '/mensagens/',
  path: '/mensagens/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelMensagensConversationIdRoute =
  PainelMensagensConversationIdRouteImport.update({
    id: '/mensagens/$conversationId',
    path: '/mensagens/$conversationId',
    getParentRoute: () => PainelRoute,
  } as any)
const ProfissionaisCitySlugProfileSlugRoute =
  ProfissionaisCitySlugProfileSlugRouteImport.update({
    id: '/profissionais/$citySlug/$profileSlug',
    path: '/profissionais/$citySlug/$profileSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/$categorySlug/$citySlug': typeof CategorySlugCitySlugRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/carteira': typeof PainelCarteiraRoute
  '/painel/disponibilidade': typeof PainelDisponibilidadeRoute
  '/painel/notificacoes': typeof PainelNotificacoesRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/painel/': typeof PainelIndexRoute
  '/painel/disputas/$disputeId': typeof PainelDisputasDisputeIdRoute
  '/painel/mensagens/$conversationId': typeof PainelMensagensConversationIdRoute
  '/profissionais/$citySlug/$profileSlug': typeof ProfissionaisCitySlugProfileSlugRoute
  '/painel/mensagens/': typeof PainelMensagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/onboarding': typeof OnboardingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/$categorySlug/$citySlug': typeof CategorySlugCitySlugRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/carteira': typeof PainelCarteiraRoute
  '/painel/disponibilidade': typeof PainelDisponibilidadeRoute
  '/painel/notificacoes': typeof PainelNotificacoesRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/painel': typeof PainelIndexRoute
  '/painel/disputas/$disputeId': typeof PainelDisputasDisputeIdRoute
  '/painel/mensagens/$conversationId': typeof PainelMensagensConversationIdRoute
  '/profissionais/$citySlug/$profileSlug': typeof ProfissionaisCitySlugProfileSlugRoute
  '/painel/mensagens': typeof PainelMensagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/$categorySlug/$citySlug': typeof CategorySlugCitySlugRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/carteira': typeof PainelCarteiraRoute
  '/painel/disponibilidade': typeof PainelDisponibilidadeRoute
  '/painel/notificacoes': typeof PainelNotificacoesRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/painel/': typeof PainelIndexRoute
  '/painel/disputas/$disputeId': typeof PainelDisputasDisputeIdRoute
  '/painel/mensagens/$conversationId': typeof PainelMensagensConversationIdRoute
  '/profissionais/$citySlug/$profileSlug': typeof ProfissionaisCitySlugProfileSlugRoute
  '/painel/mensagens/': typeof PainelMensagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/cadastro'
    | '/entrar'
    | '/onboarding'
    | '/painel'
    | '/recuperar-senha'
    | '/$categorySlug/$citySlug'
    | '/painel/agenda'
    | '/painel/carteira'
    | '/painel/disponibilidade'
    | '/painel/notificacoes'
    | '/painel/perfil'
    | '/painel/servicos'
    | '/painel/'
    | '/painel/disputas/$disputeId'
    | '/painel/mensagens/$conversationId'
    | '/profissionais/$citySlug/$profileSlug'
    | '/painel/mensagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/cadastro'
    | '/entrar'
    | '/onboarding'
    | '/recuperar-senha'
    | '/$categorySlug/$citySlug'
    | '/painel/agenda'
    | '/painel/carteira'
    | '/painel/disponibilidade'
    | '/painel/notificacoes'
    | '/painel/perfil'
    | '/painel/servicos'
    | '/painel'
    | '/painel/disputas/$disputeId'
    | '/painel/mensagens/$conversationId'
    | '/profissionais/$citySlug/$profileSlug'
    | '/painel/mensagens'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/cadastro'
    | '/entrar'
    | '/onboarding'
    | '/painel'
    | '/recuperar-senha'
    | '/$categorySlug/$citySlug'
    | '/painel/agenda'
    | '/painel/carteira'
    | '/painel/disponibilidade'
    | '/painel/notificacoes'
    | '/painel/perfil'
    | '/painel/servicos'
    | '/painel/'
    | '/painel/disputas/$disputeId'
    | '/painel/mensagens/$conversationId'
    | '/profissionais/$citySlug/$profileSlug'
    | '/painel/mensagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  OnboardingRoute: typeof OnboardingRoute
  PainelRoute: typeof PainelRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  CategorySlugCitySlugRoute: typeof CategorySlugCitySlugRoute
  ProfissionaisCitySlugProfileSlugRoute: typeof ProfissionaisCitySlugProfileSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categorySlug/$citySlug': {
      id: '/$categorySlug/$citySlug'
      path: '/$categorySlug/$citySlug'
      fullPath: '/$categorySlug/$citySlug'
      preLoaderRoute: typeof CategorySlugCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/agenda': {
      id: '/painel/agenda'
      path: '/agenda'
      fullPath: '/painel/agenda'
      preLoaderRoute: typeof PainelAgendaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/carteira': {
      id: '/painel/carteira'
      path: '/carteira'
      fullPath: '/painel/carteira'
      preLoaderRoute: typeof PainelCarteiraRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/disponibilidade': {
      id: '/painel/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/painel/disponibilidade'
      preLoaderRoute: typeof PainelDisponibilidadeRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/notificacoes': {
      id: '/painel/notificacoes'
      path: '/notificacoes'
      fullPath: '/painel/notificacoes'
      preLoaderRoute: typeof PainelNotificacoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/perfil': {
      id: '/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof PainelPerfilRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/servicos': {
      id: '/painel/servicos'
      path: '/servicos'
      fullPath: '/painel/servicos'
      preLoaderRoute: typeof PainelServicosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/disputas/$disputeId': {
      id: '/painel/disputas/$disputeId'
      path: '/disputas/$disputeId'
      fullPath: '/painel/disputas/$disputeId'
      preLoaderRoute: typeof PainelDisputasDisputeIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/mensagens/': {
      id: '/painel/mensagens/'
      path: '/mensagens'
      fullPath: '/painel/mensagens/'
      preLoaderRoute: typeof PainelMensagensIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/mensagens/$conversationId': {
      id: '/painel/mensagens/$conversationId'
      path: '/mensagens/$conversationId'
      fullPath: '/painel/mensagens/$conversationId'
      preLoaderRoute: typeof PainelMensagensConversationIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/profissionais/$citySlug/$profileSlug': {
      id: '/profissionais/$citySlug/$profileSlug'
      path: '/profissionais/$citySlug/$profileSlug'
      fullPath: '/profissionais/$citySlug/$profileSlug'
      preLoaderRoute: typeof ProfissionaisCitySlugProfileSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PainelRouteChildren {
  PainelAgendaRoute: typeof PainelAgendaRoute
  PainelCarteiraRoute: typeof PainelCarteiraRoute
  PainelDisponibilidadeRoute: typeof PainelDisponibilidadeRoute
  PainelNotificacoesRoute: typeof PainelNotificacoesRoute
  PainelPerfilRoute: typeof PainelPerfilRoute
  PainelServicosRoute: typeof PainelServicosRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelDisputasDisputeIdRoute: typeof PainelDisputasDisputeIdRoute
  PainelMensagensConversationIdRoute: typeof PainelMensagensConversationIdRoute
  PainelMensagensIndexRoute: typeof PainelMensagensIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAgendaRoute: PainelAgendaRoute,
  PainelCarteiraRoute: PainelCarteiraRoute,
  PainelDisponibilidadeRoute: PainelDisponibilidadeRoute,
  PainelNotificacoesRoute: PainelNotificacoesRoute,
  PainelPerfilRoute: PainelPerfilRoute,
  PainelServicosRoute: PainelServicosRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelDisputasDisputeIdRoute: PainelDisputasDisputeIdRoute,
  PainelMensagensConversationIdRoute: PainelMensagensConversationIdRoute,
  PainelMensagensIndexRoute: PainelMensagensIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  OnboardingRoute: OnboardingRoute,
  PainelRoute: PainelRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  CategorySlugCitySlugRoute: CategorySlugCitySlugRoute,
  ProfissionaisCitySlugProfileSlugRoute: ProfissionaisCitySlugProfileSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
