/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as CategorySlugCitySlugRouteImport } from './routes/$categorySlug.$citySlug'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelAgendaRouteImport } from './routes/painel.agenda'
import { Route as PainelCarteiraRouteImport } from './routes/painel.carteira'
import { Route as PainelDisponibilidadeRouteImport } from './routes/painel.disponibilidade'
import { Route as PainelPerfilRouteImport } from './routes/painel.perfil'
import { Route as PainelServicosRouteImport } from './routes/painel.servicos'
import { Route as ProfissionaisCitySlugProfileSlugRouteImport } from './routes/profissionais.$citySlug.$profileSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugCitySlugRoute = CategorySlugCitySlugRouteImport.update({
  id: '/$categorySlug/$citySlug',
  path: '/$categorySlug/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAgendaRoute = PainelAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCarteiraRoute = PainelCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => PainelRoute,
} as any)
const PainelDisponibilidadeRoute = PainelDisponibilidadeRouteImport.update({
  id: '/disponibilidade',
  path: '/disponibilidade',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPerfilRoute = PainelPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PainelRoute,
} as any)
const PainelServicosRoute = PainelServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => PainelRoute,
} as any)
const ProfissionaisCitySlugProfileSlugRoute =
  ProfissionaisCitySlugProfileSlugRouteImport.update({
    id: '/profissionais/$citySlug/$profileSlug',
    path: '/profissionais/$citySlug/$profileSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/$categorySlug/$citySlug': typeof CategorySlugCitySlugRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/carteira': typeof PainelCarteiraRoute
  '/painel/disponibilidade': typeof PainelDisponibilidadeRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/painel/': typeof PainelIndexRoute
  '/profissionais/$citySlug/$profileSlug': typeof ProfissionaisCitySlugProfileSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/onboarding': typeof OnboardingRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/$categorySlug/$citySlug': typeof CategorySlugCitySlugRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/carteira': typeof PainelCarteiraRoute
  '/painel/disponibilidade': typeof PainelDisponibilidadeRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/painel': typeof PainelIndexRoute
  '/profissionais/$citySlug/$profileSlug': typeof ProfissionaisCitySlugProfileSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRouteWithChildren
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/$categorySlug/$citySlug': typeof CategorySlugCitySlugRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/carteira': typeof PainelCarteiraRoute
  '/painel/disponibilidade': typeof PainelDisponibilidadeRoute
  '/painel/perfil': typeof PainelPerfilRoute
  '/painel/servicos': typeof PainelServicosRoute
  '/painel/': typeof PainelIndexRoute
  '/profissionais/$citySlug/$profileSlug': typeof ProfissionaisCitySlugProfileSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/cadastro'
    | '/entrar'
    | '/onboarding'
    | '/painel'
    | '/recuperar-senha'
    | '/$categorySlug/$citySlug'
    | '/painel/agenda'
    | '/painel/carteira'
    | '/painel/disponibilidade'
    | '/painel/perfil'
    | '/painel/servicos'
    | '/painel/'
    | '/profissionais/$citySlug/$profileSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/cadastro'
    | '/entrar'
    | '/onboarding'
    | '/recuperar-senha'
    | '/$categorySlug/$citySlug'
    | '/painel/agenda'
    | '/painel/carteira'
    | '/painel/disponibilidade'
    | '/painel/perfil'
    | '/painel/servicos'
    | '/painel'
    | '/profissionais/$citySlug/$profileSlug'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/cadastro'
    | '/entrar'
    | '/onboarding'
    | '/painel'
    | '/recuperar-senha'
    | '/$categorySlug/$citySlug'
    | '/painel/agenda'
    | '/painel/carteira'
    | '/painel/disponibilidade'
    | '/painel/perfil'
    | '/painel/servicos'
    | '/painel/'
    | '/profissionais/$citySlug/$profileSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  OnboardingRoute: typeof OnboardingRoute
  PainelRoute: typeof PainelRouteWithChildren
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  CategorySlugCitySlugRoute: typeof CategorySlugCitySlugRoute
  ProfissionaisCitySlugProfileSlugRoute: typeof ProfissionaisCitySlugProfileSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categorySlug/$citySlug': {
      id: '/$categorySlug/$citySlug'
      path: '/$categorySlug/$citySlug'
      fullPath: '/$categorySlug/$citySlug'
      preLoaderRoute: typeof CategorySlugCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/agenda': {
      id: '/painel/agenda'
      path: '/agenda'
      fullPath: '/painel/agenda'
      preLoaderRoute: typeof PainelAgendaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/carteira': {
      id: '/painel/carteira'
      path: '/carteira'
      fullPath: '/painel/carteira'
      preLoaderRoute: typeof PainelCarteiraRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/disponibilidade': {
      id: '/painel/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/painel/disponibilidade'
      preLoaderRoute: typeof PainelDisponibilidadeRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/perfil': {
      id: '/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof PainelPerfilRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/servicos': {
      id: '/painel/servicos'
      path: '/servicos'
      fullPath: '/painel/servicos'
      preLoaderRoute: typeof PainelServicosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/profissionais/$citySlug/$profileSlug': {
      id: '/profissionais/$citySlug/$profileSlug'
      path: '/profissionais/$citySlug/$profileSlug'
      fullPath: '/profissionais/$citySlug/$profileSlug'
      preLoaderRoute: typeof ProfissionaisCitySlugProfileSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PainelRouteChildren {
  PainelAgendaRoute: typeof PainelAgendaRoute
  PainelCarteiraRoute: typeof PainelCarteiraRoute
  PainelDisponibilidadeRoute: typeof PainelDisponibilidadeRoute
  PainelPerfilRoute: typeof PainelPerfilRoute
  PainelServicosRoute: typeof PainelServicosRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAgendaRoute: PainelAgendaRoute,
  PainelCarteiraRoute: PainelCarteiraRoute,
  PainelDisponibilidadeRoute: PainelDisponibilidadeRoute,
  PainelPerfilRoute: PainelPerfilRoute,
  PainelServicosRoute: PainelServicosRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  OnboardingRoute: OnboardingRoute,
  PainelRoute: PainelRouteWithChildren,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  CategorySlugCitySlugRoute: CategorySlugCitySlugRoute,
  ProfissionaisCitySlugProfileSlugRoute: ProfissionaisCitySlugProfileSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
